const errorTypes = {
  MAX_SIZE_REACHED: "MAX_SIZE_REACHED",
  COULD_NOT_CREATE_TRANSACTION_UNSPENT_OUTPUT: "COULD_NOT_CREATE_TRANSACTION_UNSPENT_OUTPUT",
  COULD_NOT_SERIALIZE_TRANSACTION_UNSPENT_OUTPUT: "COULD_NOT_SERIALIZE_TRANSACTION_UNSPENT_OUTPUT",
};

export default errorTypes;
