export const MARKET_TYPE = {
  'NEW_LISTING': 'NEW_LISTING',
  'NEW_LISTING_SUCCESS': 'NEW_LISTING_SUCCESS',
  'PRICE_UPDATE': 'PRICE_UPDATE',
  'PRICE_UPDATE_SUCCESS': 'PRICE_UPDATE_SUCCESS',
  'DELIST': 'DELIST',
  'DELIST_SUCCESS': 'DELIST_SUCCESS',
  'PURCHASE': 'PURCHASE',
  'PURCHASE_SUCCESS': 'PURCHASE_SUCCESS',
}
