export const COLLECTIONS_LOADED = 'COLLECTIONS_LOADED';
export const COLLECTIONS_LISTING_LOADED = 'COLLECTIONS_LISTING_LOADED';
export const COLLECTIONS_ADD_TOKENS = 'COLLECTIONS_ADD_TOKENS';
export const COLLECTIONS_ADD_TOKEN = 'COLLECTIONS_ADD_TOKEN';
export const COLLECTIONS_LOADING = 'COLLECTIONS_LOADING';
export const COLLECTIONS_TOP_PROJECTS = 'COLLECTIONS_TOP_PROJECTS';
export const COLLECTIONS_ADD_ASSETS = 'COLLECTIONS_ADD_ASSETS';
