const errorTypes = {
  TRANSACTION_FAILED_SO_MANY_UTXOS: "TRANSACTION_FAILED_SO_MANY_UTXOS",
  TRANSACTION_FAILED_NOT_ENOUGH_FUNDS: "TRANSACTION_FAILED_NOT_ENOUGH_FUNDS",
  TRANSACTION_FAILED_CHANGE_TOO_SMALL: "TRANSACTION_FAILED_CHANGE_TOO_SMALL",
  TRANSACTION_FAILED_MAX_TX_SIZE_REACHED: "TRANSACTION_FAILED_MAX_TX_SIZE_REACHED",
  TRANSACTION_FAILED_ASSET_NOT_SPENDABLE: "TRANSACTION_FAILED_ASSET_NOT_SPENDABLE",
};

export default errorTypes;
